yarnPath: .yarn/releases/yarn-4.0.2.cjs

npmRegistries:
  "https://npm.pkg.github.com/":
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_PERSONAL_ACCESS_TOKEN_CLASSIC-''}

npmScopes:
  bya2:
    npmRegistryServer: https://npm.pkg.github.com